package kelyan.offerte;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AttachmentList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Id")
   private String id;
   @org.kie.api.definition.type.Label("Descrizione")
   private java.lang.String descrizione;
   @org.kie.api.definition.type.Label("Classe")
   private java.lang.String classe;

   public AttachmentList()
   {
   }

   public java.lang.String getClasse()
   {
      return this.classe;
   }

   public void setClasse(java.lang.String classe)
   {
      this.classe = classe;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getDescrizione()
   {
      return this.descrizione;
   }

   public void setDescrizione(java.lang.String descrizione)
   {
      this.descrizione = descrizione;
   }

   public AttachmentList(java.lang.String id, java.lang.String descrizione,
         java.lang.String classe)
   {
      this.id = id;
      this.descrizione = descrizione;
      this.classe = classe;
   }

}