package kelyan.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DO_prova implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String primo;
   private java.lang.Integer secondo;
   private java.util.Date terzo;

   public DO_prova()
   {
   }

   public java.lang.String getPrimo()
   {
      return this.primo;
   }

   public void setPrimo(java.lang.String primo)
   {
      this.primo = primo;
   }

   public java.lang.Integer getSecondo()
   {
      return this.secondo;
   }

   public void setSecondo(java.lang.Integer secondo)
   {
      this.secondo = secondo;
   }

   public java.util.Date getTerzo()
   {
      return this.terzo;
   }

   public void setTerzo(java.util.Date terzo)
   {
      this.terzo = terzo;
   }

   public DO_prova(java.lang.String primo, java.lang.Integer secondo,
         java.util.Date terzo)
   {
      this.primo = primo;
      this.secondo = secondo;
      this.terzo = terzo;
   }

}