package kelyan.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestDO1 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "s1")
   private java.lang.String s1;
   @org.kie.api.definition.type.Label(value = "i1")
   private java.lang.Integer i1;
   @org.kie.api.definition.type.Label(value = "f1")
   private java.lang.Float f1;
   @org.kie.api.definition.type.Label(value = "d1")
   private java.math.BigDecimal d1;

   public TestDO1()
   {
   }

   public java.lang.String getS1()
   {
      return this.s1;
   }

   public void setS1(java.lang.String s1)
   {
      this.s1 = s1;
   }

   public java.lang.Integer getI1()
   {
      return this.i1;
   }

   public void setI1(java.lang.Integer i1)
   {
      this.i1 = i1;
   }

   public java.lang.Float getF1()
   {
      return this.f1;
   }

   public void setF1(java.lang.Float f1)
   {
      this.f1 = f1;
   }

   public java.math.BigDecimal getD1()
   {
      return this.d1;
   }

   public void setD1(java.math.BigDecimal d1)
   {
      this.d1 = d1;
   }

   public TestDO1(java.lang.String s1, java.lang.Integer i1,
         java.lang.Float f1, java.math.BigDecimal d1)
   {
      this.s1 = s1;
      this.i1 = i1;
      this.f1 = f1;
      this.d1 = d1;
   }

}