package kelyan.rda;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GeneralInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Data RdA")
   private String rdaDate;

   @org.kie.api.definition.type.Label("Numero RdA")
   private java.lang.String rdaNumber;

   @org.kie.api.definition.type.Label("Azienda richiedente")
   private java.lang.String company;

   @org.kie.api.definition.type.Label("Interlocutore")
   private java.lang.String operator;

   @org.kie.api.definition.type.Label("Oggetto RdA")
   private java.lang.String object;

   @org.kie.api.definition.type.Label("Motivazione del fabbisogno")
   private java.lang.String reason;

   public GeneralInfo()
   {
   }

   public java.lang.String getRdaNumber()
   {
      return this.rdaNumber;
   }

   public void setRdaNumber(java.lang.String rdaNumber)
   {
      this.rdaNumber = rdaNumber;
   }

   public java.lang.String getCompany()
   {
      return this.company;
   }

   public void setCompany(java.lang.String company)
   {
      this.company = company;
   }

   public java.lang.String getOperator()
   {
      return this.operator;
   }

   public void setOperator(java.lang.String operator)
   {
      this.operator = operator;
   }

   public java.lang.String getObject()
   {
      return this.object;
   }

   public void setObject(java.lang.String object)
   {
      this.object = object;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getRdaDate()
   {
      return this.rdaDate;
   }

   public void setRdaDate(java.lang.String rdaDate)
   {
      this.rdaDate = rdaDate;
   }

   public GeneralInfo(java.lang.String rdaDate, java.lang.String rdaNumber,
         java.lang.String company, java.lang.String operator,
         java.lang.String object, java.lang.String reason)
   {
      this.rdaDate = rdaDate;
      this.rdaNumber = rdaNumber;
      this.company = company;
      this.operator = operator;
      this.object = object;
      this.reason = reason;
   }

}