package kelyan.rda;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class rda implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Informazioni Generali")
   private kelyan.rda.GeneralInfo generalInfo;

   @org.kie.api.definition.type.Label("Dettaglio RdA")
   private java.util.List<kelyan.rda.rdaLine> rdaLines;

   @org.kie.api.definition.type.Label("Importo RdA")
   private java.lang.Float rdaAmount;

   @org.kie.api.definition.type.Label("Allegati")
   private java.util.List<java.lang.String> files;

   @org.kie.api.definition.type.Label("Progetto autorizzato")
   private String projectAutorization;

   @org.kie.api.definition.type.Label("Modivo della non autorizzazione")
   private java.lang.String reasonAutorization;

   @org.kie.api.definition.type.Label("Copertura Budget")
   private String budgetAutorization;

   @org.kie.api.definition.type.Label("Esigenza del cliente")
   private Boolean customerNeed;

   public rda()
   {
   }

   public kelyan.rda.GeneralInfo getGeneralInfo()
   {
      return this.generalInfo;
   }

   public void setGeneralInfo(kelyan.rda.GeneralInfo generalInfo)
   {
      this.generalInfo = generalInfo;
   }

   public java.util.List<kelyan.rda.rdaLine> getRdaLines()
   {
      return this.rdaLines;
   }

   public void setRdaLines(java.util.List<kelyan.rda.rdaLine> rdaLines)
   {
      this.rdaLines = rdaLines;
   }

   public java.lang.Float getRdaAmount()
   {
      return this.rdaAmount;
   }

   public void setRdaAmount(java.lang.Float rdaAmount)
   {
      this.rdaAmount = rdaAmount;
   }

   public java.util.List<java.lang.String> getFiles()
   {
      return this.files;
   }

   public void setFiles(java.util.List<java.lang.String> files)
   {
      this.files = files;
   }

   public java.lang.String getReasonAutorization()
   {
      return this.reasonAutorization;
   }

   public void setReasonAutorization(java.lang.String reasonAutorization)
   {
      this.reasonAutorization = reasonAutorization;
   }

   public java.lang.String getProjectAutorization()
   {
      return this.projectAutorization;
   }

   public void setProjectAutorization(java.lang.String projectAutorization)
   {
      this.projectAutorization = projectAutorization;
   }

   public java.lang.Boolean getCustomerNeed()
   {
      return this.customerNeed;
   }

   public void setCustomerNeed(java.lang.Boolean customerNeed)
   {
      this.customerNeed = customerNeed;
   }

   public java.lang.String getBudgetAutorization()
   {
      return this.budgetAutorization;
   }

   public void setBudgetAutorization(java.lang.String budgetAutorization)
   {
      this.budgetAutorization = budgetAutorization;
   }

   public rda(kelyan.rda.GeneralInfo generalInfo,
         java.util.List<kelyan.rda.rdaLine> rdaLines, java.lang.Float rdaAmount,
         java.util.List<java.lang.String> files,
         java.lang.String projectAutorization,
         java.lang.String reasonAutorization,
         java.lang.String budgetAutorization, java.lang.Boolean customerNeed)
   {
      this.generalInfo = generalInfo;
      this.rdaLines = rdaLines;
      this.rdaAmount = rdaAmount;
      this.files = files;
      this.projectAutorization = projectAutorization;
      this.reasonAutorization = reasonAutorization;
      this.budgetAutorization = budgetAutorization;
      this.customerNeed = customerNeed;
   }

}