package kelyan.offerte;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OfferDataObj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Data Offerta")
   private String dateOffer;

   @org.kie.api.definition.type.Label("Agente")
   private java.lang.String userCreator;

   @org.kie.api.definition.type.Label("Codice Utente")
   private java.lang.String codClient;

   @org.kie.api.definition.type.Label("N.Fax")
   private java.lang.String faxClient;

   @org.kie.api.definition.type.Label("E-mail Cliente")
   private java.lang.String mailClient;

   @org.kie.api.definition.type.Label("Annotazioni")
   private java.lang.String note;

   @org.kie.api.definition.type.Label("Prodotti")
   private java.util.List<kelyan.offerte.ProductDataObj> prodList;

   @org.kie.api.definition.type.Label("Offerta Numero")
   private java.lang.Integer n;

   @org.kie.api.definition.type.Label("Parere")
   private java.lang.String opinion;

   @org.kie.api.definition.type.Label("Motivazione Parere")
   private java.lang.String reason;

   @org.kie.api.definition.type.Label("Verifica Finale")
   private java.lang.String finalOpinion;

   @org.kie.api.definition.type.Label("idKfiles")
   private java.lang.String idKfiles;

   @org.kie.api.definition.type.Label("Tipo Invio")
   private java.lang.String sendType;

   @org.kie.api.definition.type.Label("Errore")
   private java.lang.String errorDescription;

   @org.kie.api.definition.type.Label("TotProdotti")
   private Double totProdotti;

   @org.kie.api.definition.type.Label(value = "Ragione Sociale")
   private java.lang.String ragsocClient;

   public OfferDataObj()
   {
   }

   public java.lang.String getUserCreator()
   {
      return this.userCreator;
   }

   public void setUserCreator(java.lang.String userCreator)
   {
      this.userCreator = userCreator;
   }

   public java.lang.String getCodClient()
   {
      return this.codClient;
   }

   public void setCodClient(java.lang.String codClient)
   {
      this.codClient = codClient;
   }

   public java.lang.String getFaxClient()
   {
      return this.faxClient;
   }

   public void setFaxClient(java.lang.String faxClient)
   {
      this.faxClient = faxClient;
   }

   public java.lang.String getMailClient()
   {
      return this.mailClient;
   }

   public void setMailClient(java.lang.String mailClient)
   {
      this.mailClient = mailClient;
   }

   public java.lang.String getNote()
   {
      return this.note;
   }

   public void setNote(java.lang.String note)
   {
      this.note = note;
   }

   public java.util.List<kelyan.offerte.ProductDataObj> getProdList()
   {
      return this.prodList;
   }

   public void setProdList(java.util.List<kelyan.offerte.ProductDataObj> prodList)
   {
      this.prodList = prodList;
   }

   public java.lang.Integer getN()
   {
      return this.n;
   }

   public void setN(java.lang.Integer n)
   {
      this.n = n;
   }

   public java.lang.String getOpinion()
   {
      return this.opinion;
   }

   public void setOpinion(java.lang.String opinion)
   {
      this.opinion = opinion;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getFinalOpinion()
   {
      return this.finalOpinion;
   }

   public void setFinalOpinion(java.lang.String finalOpinion)
   {
      this.finalOpinion = finalOpinion;
   }

   public java.lang.String getIdKfiles()
   {
      return this.idKfiles;
   }

   public void setIdKfiles(java.lang.String idKfiles)
   {
      this.idKfiles = idKfiles;
   }

   public java.lang.String getSendType()
   {
      return this.sendType;
   }

   public void setSendType(java.lang.String sendType)
   {
      this.sendType = sendType;
   }

   public java.lang.String getErrorDescription()
   {
      return this.errorDescription;
   }

   public void setErrorDescription(java.lang.String errorDescription)
   {
      this.errorDescription = errorDescription;
   }

   public java.lang.String getDateOffer()
   {
      return this.dateOffer;
   }

   public void setDateOffer(java.lang.String dateOffer)
   {
      this.dateOffer = dateOffer;
   }

   public java.lang.Double getTotProdotti()
   {
      return this.totProdotti;
   }

   public void setTotProdotti(java.lang.Double totProdotti)
   {
      this.totProdotti = totProdotti;
   }

   public java.lang.String getRagsocClient()
   {
      return this.ragsocClient;
   }

   public void setRagsocClient(java.lang.String ragsocClient)
   {
      this.ragsocClient = ragsocClient;
   }

   public OfferDataObj(java.lang.String dateOffer, java.lang.String userCreator,
         java.lang.String codClient, java.lang.String faxClient,
         java.lang.String mailClient, java.lang.String note,
         java.util.List<kelyan.offerte.ProductDataObj> prodList,
         java.lang.Integer n, java.lang.String opinion, java.lang.String reason,
         java.lang.String finalOpinion, java.lang.String idKfiles,
         java.lang.String sendType, java.lang.String errorDescription,
         java.lang.Double totProdotti, java.lang.String ragsocClient)
   {
      this.dateOffer = dateOffer;
      this.userCreator = userCreator;
      this.codClient = codClient;
      this.faxClient = faxClient;
      this.mailClient = mailClient;
      this.note = note;
      this.prodList = prodList;
      this.n = n;
      this.opinion = opinion;
      this.reason = reason;
      this.finalOpinion = finalOpinion;
      this.idKfiles = idKfiles;
      this.sendType = sendType;
      this.errorDescription = errorDescription;
      this.totProdotti = totProdotti;
      this.ragsocClient = ragsocClient;
   }

}