package kelyan.offerte;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductDataObj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Cod. Prodotto")
   private java.lang.String codProd;
   @org.kie.api.definition.type.Label("Descrizione")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Qta")
   private java.lang.Integer qta;
   @org.kie.api.definition.type.Label("Prezzo")
   private Float price;
   @org.kie.api.definition.type.Label("Totale")
   private Float total;

   public ProductDataObj()
   {
   }

   public java.lang.String getCodProd()
   {
      return this.codProd;
   }

   public void setCodProd(java.lang.String codProd)
   {
      this.codProd = codProd;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Integer getQta()
   {
      return this.qta;
   }

   public void setQta(java.lang.Integer qta)
   {
      this.qta = qta;
   }

   public java.lang.Float getTotal()
   {
      return this.total;
   }

   public void setTotal(java.lang.Float total)
   {
      this.total = total;
   }

   public java.lang.Float getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Float price)
   {
      this.price = price;
   }

   public ProductDataObj(java.lang.String codProd, java.lang.String description,
         java.lang.Integer qta, java.lang.Float price, java.lang.Float total)
   {
      this.codProd = codProd;
      this.description = description;
      this.qta = qta;
      this.price = price;
      this.total = total;
   }

}